# -*- coding: utf-8 -*-
"""demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hqi6xuWL7MWH-FBrecGmKtbXfBJJF8qh
"""

import requests

url = "https://api-inference.huggingface.co/models/BAAI/bge-base-en/top2"

phrases = ["apple", "banana", "orange", "kiwi", "peach"]
payload = [{"phrase": phrase} for phrase in phrases]

response = requests.post(url, json=payload)

print(f"Top 2 closest phrases: {response.json()['phrase_pairs'][0].phrase1}, {response.json()['phrase_pairs'][0].phrase2}")

import requests
url = "http://127.0.0.1:8000" # this is the local host url that my api supposed to work on

# Define a hard-coded list of phrases
phrases = [
    "The sky is blue",
    "The sun is yellow",
    "The grass is green",
    "The moon is white",
    "The sea is blue",
    "The rose is red"
]

# Send a POST request to the API with the list of phrases as JSON payload
response = requests.post(url, json={"phrases": phrases})

# Print the top 2 closest phrases returned by the API
print(response.json())