# -*- coding: utf-8 -*-
"""pylint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IVQVHOejpMGkVnak-spQAVorRYMLz4pE
"""

pip install pylint==2.10.0

import pylint.lint
import pylint

!touch .pylintrc # form pylint object

!pylint api.py # test api.py

!pylint demo.py # test demo.py